// Room and Faculty Data for Digital Signage Application

const buildingData = {
  floors: [
    {
      id: 1,
      name: "Floor 1",
      rooms: [
        { number: "101", name: "Faculty Office", department: "General", occupant: "Dr. Smith", color: "#FFF9E6" },
        { number: "102", name: "Faculty Office", department: "General", occupant: "Dr. Johnson", color: "#FFF9E6" },
        { number: "103", name: "Large Classroom", department: "General Education", occupant: "", color: "#FFF9E6" },
        { number: "105", name: "Computer Lab", department: "Technology", occupant: "", color: "#7DD046" },
        { number: "106", name: "Office", department: "General", occupant: "Dr. Williams", color: "#FFF9E6" },
        { number: "108", name: "Classroom", department: "General Education", occupant: "", color: "#FFF9E6" },
        { number: "109", name: "Office", department: "General", occupant: "Dr. Brown", color: "#FFF9E6" },
        { number: "111", name: "Science Lab", department: "Sciences", occupant: "", color: "#7DD046" },
        { number: "117", name: "Office", department: "General", occupant: "Dr. Davis", color: "#FFF9E6" },
        { number: "118", name: "Men's Restroom", department: "Facilities", occupant: "", color: "#76F6E9" },
        { number: "119", name: "Women's Restroom", department: "Facilities", occupant: "", color: "#74D5F6" },
        { number: "120", name: "Classroom", department: "General Education", occupant: "", color: "#FFF9E6" },
        { number: "121", name: "Office", department: "General", occupant: "Dr. Miller", color: "#FFF9E6" },
        { number: "122", name: "Conference Room", department: "Administration", occupant: "", color: "#FA8BED" },
        { number: "123", name: "Office", department: "General", occupant: "Dr. Wilson", color: "#FFF9E6" },
        { number: "124", name: "Classroom", department: "General Education", occupant: "", color: "#FFF9E6" },
        { number: "125", name: "Office", department: "General", occupant: "Dr. Moore", color: "#FFF9E6" },
        { number: "126", name: "Classroom", department: "General Education", occupant: "", color: "#FFF9E6" },
        { number: "127", name: "Office", department: "General", occupant: "Dr. Taylor", color: "#FFF9E6" },
        { number: "130", name: "Elevator", department: "Facilities", occupant: "", color: "#4A90E2" },
        { number: "131", name: "Stairs", department: "Facilities", occupant: "", color: "#4A90E2" },
        { number: "132", name: "Stairs", department: "Facilities", occupant: "", color: "#4A90E2" },
        { number: "133", name: "Elevator", department: "Facilities", occupant: "", color: "#4A90E2" },
        { number: "134", name: "Utility", department: "Facilities", occupant: "", color: "#4A90E2" },
        { number: "135", name: "Office", department: "General", occupant: "Dr. Anderson", color: "#FFF9E6" },
        { number: "137", name: "Office", department: "General", occupant: "Dr. Thomas", color: "#FFF9E6" }
      ]
    },
    {
      id: 2,
      name: "Floor 2",
      rooms: [
        { number: "201", name: "Admissions & Records", department: "Admissions & Records", occupant: "Main Office", color: "#FFD700" },
        { number: "202", name: "Financial Aid Office", department: "Financial Aid Office", occupant: "Main Office", color: "#FFD700" },
        { number: "203", name: "Business Administration", department: "Business Administration", occupant: "Department Office", color: "#FFD700" },
        { number: "204", name: "Hawaiian Studies", department: "Hawaiian Studies", occupant: "Department Office", color: "#FFD700" },
        { number: "206", name: "Office", department: "Hospitality Faculty", occupant: "Faculty Office", color: "#FFF9E6" },
        { number: "207", name: "Large Classroom", department: "General Education", occupant: "", color: "#FFF9E6" },
        { number: "208", name: "Classroom", department: "General Education", occupant: "", color: "#FFF9E6" },
        { number: "209", name: "Office", department: "Hospitality Faculty", occupant: "Dr. Garcia", color: "#FFF9E6" },
        { number: "211", name: "Office", department: "Hospitality Faculty", occupant: "Dr. Martinez", color: "#FFF9E6" },
        { number: "212", name: "Classroom", department: "General Education", occupant: "", color: "#FFF9E6" },
        { number: "213", name: "Office", department: "Hospitality Faculty", occupant: "Dr. Rodriguez", color: "#FFF9E6" },
        { number: "214", name: "Office", department: "Hospitality Faculty", occupant: "Dr. Hernandez", color: "#FFF9E6" },
        { number: "215", name: "Conference Room", department: "Administration", occupant: "", color: "#FA8BED" },
        { number: "216", name: "Office", department: "Hospitality Faculty", occupant: "Dr. Lopez", color: "#FFF9E6" },
        { number: "217", name: "Office", department: "Hospitality Faculty", occupant: "Dr. Gonzalez", color: "#FFF9E6" },
        { number: "218", name: "Office", department: "Hospitality Faculty", occupant: "Dr. Perez", color: "#FFF9E6" },
        { number: "219", name: "Men's Restroom", department: "Facilities", occupant: "", color: "#76F6E9" },
        { number: "220", name: "Women's Restroom", department: "Facilities", occupant: "", color: "#74D5F6" },
        { number: "221", name: "Office", department: "General", occupant: "Dr. Sanchez", color: "#FFF9E6" },
        { number: "230", name: "Elevator", department: "Facilities", occupant: "", color: "#4A90E2" },
        { number: "231", name: "Stairs", department: "Facilities", occupant: "", color: "#7DD046" },
        { number: "232", name: "Office", department: "General", occupant: "Dr. Ramirez", color: "#FFF9E6" },
        { number: "233", name: "Office", department: "General", occupant: "Dr. Torres", color: "#FFF9E6" },
        { number: "234", name: "Office", department: "General", occupant: "Dr. Flores", color: "#FFF9E6" },
        { number: "235", name: "Office", department: "General", occupant: "Dr. Rivera", color: "#FFF9E6" }
      ]
    }
  ],
  faculty: [
    { name: "Vincent", room: "209", floor: 2, department: "Hospitality Faculty", title: "Associate Professor" },
    { name: "Dr. Smith", room: "101", floor: 1, department: "General", title: "Professor" },
    { name: "Dr. Johnson", room: "102", floor: 1, department: "General", title: "Associate Professor" },
    { name: "Dr. Williams", room: "106", floor: 1, department: "General", title: "Assistant Professor" },
    { name: "Dr. Brown", room: "109", floor: 1, department: "General", title: "Professor" },
    { name: "Dr. Davis", room: "117", floor: 1, department: "General", title: "Associate Professor" },
    { name: "Dr. Miller", room: "121", floor: 1, department: "General", title: "Assistant Professor" },
    { name: "Dr. Wilson", room: "123", floor: 1, department: "General", title: "Professor" },
    { name: "Dr. Moore", room: "125", floor: 1, department: "General", title: "Associate Professor" },
    { name: "Dr. Taylor", room: "127", floor: 1, department: "General", title: "Assistant Professor" },
    { name: "Dr. Anderson", room: "135", floor: 1, department: "General", title: "Professor" },
    { name: "Dr. Thomas", room: "137", floor: 1, department: "General", title: "Associate Professor" },
    { name: "Dr. Garcia", room: "209", floor: 2, department: "Hospitality Faculty", title: "Professor" },
    { name: "Dr. Martinez", room: "211", floor: 2, department: "Hospitality Faculty", title: "Associate Professor" },
    { name: "Dr. Rodriguez", room: "213", floor: 2, department: "Hospitality Faculty", title: "Assistant Professor" },
    { name: "Dr. Hernandez", room: "214", floor: 2, department: "Hospitality Faculty", title: "Professor" },
    { name: "Dr. Lopez", room: "216", floor: 2, department: "Hospitality Faculty", title: "Associate Professor" },
    { name: "Dr. Gonzalez", room: "217", floor: 2, department: "Hospitality Faculty", title: "Assistant Professor" },
    { name: "Dr. Perez", room: "218", floor: 2, department: "Hospitality Faculty", title: "Professor" },
    { name: "Dr. Sanchez", room: "221", floor: 2, department: "General", title: "Associate Professor" },
    { name: "Dr. Ramirez", room: "232", floor: 2, department: "General", title: "Assistant Professor" },
    { name: "Dr. Torres", room: "233", floor: 2, department: "General", title: "Professor" },
    { name: "Dr. Flores", room: "234", floor: 2, department: "General", title: "Associate Professor" },
    { name: "Dr. Rivera", room: "235", floor: 2, department: "General", title: "Assistant Professor" }
  ],
  departments: [
    { name: "Admissions & Records", floor: 2, room: "201" },
    { name: "Financial Aid Office", floor: 2, room: "202" },
    { name: "Business Administration", floor: 2, room: "203" },
    { name: "Hawaiian Studies", floor: 2, room: "204" },
    { name: "Hospitality Faculty", floor: 2, room: "206" }
  ]
};
